
export const categories =
    [
        'quarto',
        'biblioteca',
        'leitura',
        'decoração',
        'livros',
        'mangas',
        'luminarias',
        'personagens',
        'casa',
        'cozinha',
        'armário',
        'fogão',
        'lavadora',
        'airfryer',
        'café',
        'sala',
        'poster',
        'video-game',
        'tapete',
        'copa',
        'toalha de mesa',
        'gaming',
        'estante',
        'teclado',
        'mouse',
        'cadeira gamer',
        'mousepad',
        'audio',
        'auto-falante',
        'soundbar'
    ]