export const groceries = [
    { name: 'Café', category: 'Café da manhã/Padaria' },
    { name: 'Biscoito', category: 'Café da manhã/Padaria' },
    { name: 'Cereais', category: 'Café da manhã/Padaria' },
    { name: 'Achocolatado', category: 'Café da manhã/Padaria' },
    { name: 'Chá', category: 'Café da manhã/Padaria' },
    { name: 'Adoçante', category: 'Café da manhã/Padaria' },
    { name: 'Açúcar', category: 'Café da manhã/Padaria' },
    { name: 'Geleia', category: 'Café da manhã/Padaria' },
    { name: 'Torrada', category: 'Café da manhã/Padaria' },
    { name: 'Pão', category: 'Café da manhã/Padaria' },
    { name: 'Pão integral', category: 'Café da manhã/Padaria' },
    { name: 'Pão de forma', category: 'Café da manhã/Padaria' },
    { name: 'Pão de forma integral', category: 'Café da manhã/Padaria' },
    { name: 'Requeijão', category: 'Café da manhã/Padaria' },
    { name: 'Manteiga', category: 'Café da manhã/Padaria' },
    { name: 'Manteiga sem sal', category: 'Café da manhã/Padaria' },
    { name: 'Manteiga com sal', category: 'Café da manhã/Padaria' },
    { name: 'Iogurte', category: 'Café da manhã/Padaria' },
    { name: 'Iogurte Grego 100g', category: 'Café da manhã/Padaria' },
    { name: 'Iogurte Grego 200g', category: 'Café da manhã/Padaria' },
    { name: 'Iogurte Grego Pote', category: 'Café da manhã/Padaria' },
    { name: 'Bolo', category: 'Café da manhã/Padaria' },

    { name: 'Arroz', category: 'Mercearia em geral e enlatados' },
    { name: 'Arroz integral 1kg', category: 'Mercearia em geral e enlatados' },
    { name: 'Arroz integral 1kg em saquinhos', category: 'Mercearia em geral e enlatados' },
    { name: 'Arroz branco 1kg', category: 'Mercearia em geral e enlatados' },
    { name: 'Arroz branco 1kg em saquinhos', category: 'Mercearia em geral e enlatados' },
    { name: 'Feijão', category: 'Mercearia em geral e enlatados' },
    { name: 'Aveia em flocos', category: 'Mercearia em geral e enlatados' },
    { name: 'Aveia em flocos 500g', category: 'Mercearia em geral e enlatados' },
    { name: 'Aveia em flocos 200g', category: 'Mercearia em geral e enlatados' },
    { name: 'Aveia em flocos 1Kg', category: 'Mercearia em geral e enlatados' },
    { name: 'Caldo de carne', category: 'Mercearia em geral e enlatados' },
    { name: 'Gelatina', category: 'Mercearia em geral e enlatados' },
    { name: 'Macarrão instantâneo', category: 'Mercearia em geral e enlatados' },
    { name: 'Farinha de trigo', category: 'Mercearia em geral e enlatados' },
    { name: 'Barra de cereal', category: 'Mercearia em geral e enlatados' },
    { name: 'Fubá', category: 'Mercearia em geral e enlatados' },
    { name: 'Grão de bico', category: 'Mercearia em geral e enlatados' },
    { name: 'Palmito', category: 'Mercearia em geral e enlatados' },
    { name: 'Ervilha', category: 'Mercearia em geral e enlatados' },
    { name: 'Milho', category: 'Mercearia em geral e enlatados' },
    { name: 'Farinha de milho', category: 'Mercearia em geral e enlatados' },
    { name: 'Farinha de rosca', category: 'Mercearia em geral e enlatados' },
    { name: 'Fermento', category: 'Mercearia em geral e enlatados' },
    { name: 'Óleo', category: 'Mercearia em geral e enlatados' },
    { name: 'Azeite', category: 'Mercearia em geral e enlatados' },
    { name: 'Amido de milho', category: 'Mercearia em geral e enlatados' },
    { name: 'Macarrão', category: 'Mercearia em geral e enlatados' },
    { name: 'Azeitona', category: 'Mercearia em geral e enlatados' },
    { name: 'Leite condensado', category: 'Mercearia em geral e enlatados' },
    { name: 'Gelatina', category: 'Mercearia em geral e enlatados' },
    { name: 'Maionese', category: 'Mercearia em geral e enlatados' },
    { name: 'Catchup e mostarda', category: 'Mercearia em geral e enlatados' },
    { name: 'Tempero pronto', category: 'Mercearia em geral e enlatados' },
    { name: 'Sal', category: 'Mercearia em geral e enlatados' },
    { name: 'Ovos', category: 'Mercearia em geral e enlatados' },
    { name: 'Ovos dúzia', category: 'Mercearia em geral e enlatados' },
    { name: 'Ovos pente', category: 'Mercearia em geral e enlatados' },
    { name: 'Queijo ralado', category: 'Mercearia em geral e enlatados' },
    { name: 'Vinagre', category: 'Mercearia em geral e enlatados' },
    { name: 'Molho de tomate', category: 'Mercearia em geral e enlatados' },
    { name: 'Atum', category: 'Mercearia em geral e enlatados' },

    { name: 'Água', category: 'Bebidas' },
    { name: 'Leite', category: 'Bebidas' },
    { name: 'Leite Semidesnatado', category: 'Bebidas' },
    { name: 'Leite desnatado', category: 'Bebidas' },
    { name: 'Leite integral', category: 'Bebidas' },
    { name: 'Refrigerante', category: 'Bebidas' },
    { name: 'Cerveja', category: 'Bebidas' },
    { name: 'Suco', category: 'Bebidas' },
    { name: 'Suco de laranja natural 500ml', category: 'Bebidas' },
    { name: 'Suco de laranja natural 1l', category: 'Bebidas' },
    { name: 'Energético', category: 'Bebidas' },

    { name: 'Bife bovino', category: 'Carnes e frios' },
    { name: 'Bisteca suína', category: 'Carnes e frios' },
    { name: 'Carne moída', category: 'Carnes e frios' },
    { name: 'Coxa e sobrecoxa de frango', category: 'Carnes e frios' },
    { name: 'Filé de frango', category: 'Carnes e frios' },
    { name: 'Linguiça', category: 'Carnes e frios' },
    { name: 'Salsicha', category: 'Carnes e frios' },
    { name: 'Nuggets', category: 'Carnes e frios' },
    { name: 'Queijo branco', category: 'Carnes e frios' },
    { name: 'Presunto', category: 'Carnes e frios' },
    { name: 'Mussarela', category: 'Carnes e frios' },
    { name: 'Peixe', category: 'Carnes e frios' },
    { name: 'Hambúrguer', category: 'Carnes e frios' },

    { name: 'Papel higiênico', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Detergente', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Sabão em pó', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Sabão em barra', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Água sanitária', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Desinfetante', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Lustra-móveis', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Saco de lixo', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Papel toalha', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Álcool', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Amaciante', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Pano de chão', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Esponja', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Palha de aço', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Multiuso', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Filme plástico', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Papel Alumínio', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Fósforo', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Filtros de papel', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Palitos de dente', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Velas', category: 'Produtos de limpeza/Utilidades' },
    { name: 'Rodo/vassoura', category: 'Produtos de limpeza/Utilidades' },

    { name: 'Sabonete', category: 'Higiene pessoal' },
    { name: 'Creme dental', category: 'Higiene pessoal' },
    { name: 'Escova de dente', category: 'Higiene pessoal' },
    { name: 'Hastes flexíveis', category: 'Higiene pessoal' },
    { name: 'Fio dental', category: 'Higiene pessoal' },
    { name: 'Absorvente', category: 'Higiene pessoal' },
    { name: 'Shampoo', category: 'Higiene pessoal' },
    { name: 'Condicionador', category: 'Higiene pessoal' },
    { name: 'Acetona', category: 'Higiene pessoal' },
    { name: 'Algodão', category: 'Higiene pessoal' },
    { name: 'Lâmina de barbear', category: 'Higiene pessoal' },
    { name: 'Desodorante', category: 'Higiene pessoal' },

    { name: 'Abacaxi', category: 'Frutas e legumes' },
    { name: 'Laranja', category: 'Frutas e legumes' },
    { name: 'Banana', category: 'Frutas e legumes' },
    { name: 'Limão', category: 'Frutas e legumes' },
    { name: 'Mamão', category: 'Frutas e legumes' },
    { name: 'Maçã', category: 'Frutas e legumes' },
    { name: 'Melão', category: 'Frutas e legumes' },
    { name: 'Melancia', category: 'Frutas e legumes' },
    { name: 'Abóbora', category: 'Frutas e legumes' },
    { name: 'Abobrinha', category: 'Frutas e legumes' },
    { name: 'Batata', category: 'Frutas e legumes' },
    { name: 'Batata Inglesa', category: 'Frutas e legumes' },
    { name: 'Batata Doce', category: 'Frutas e legumes' },
    { name: 'Tomate', category: 'Frutas e legumes' },
    { name: 'Cebola', category: 'Frutas e legumes' },
    { name: 'Alho', category: 'Frutas e legumes' },
    { name: 'Cenoura', category: 'Frutas e legumes' },
    { name: 'Pepino', category: 'Frutas e legumes' },
    { name: 'Beterraba', category: 'Frutas e legumes' },
    { name: 'Vagem', category: 'Frutas e legumes' },
    { name: 'Berinjela', category: 'Frutas e legumes' },
    { name: 'Chuchu', category: 'Frutas e legumes' },
    { name: 'Alface', category: 'Frutas e legumes' },
    { name: 'Brócolis', category: 'Frutas e legumes' },
    { name: 'Brócolis Ninja', category: 'Frutas e legumes' },
    { name: 'Rúcula', category: 'Frutas e legumes' },
    { name: 'Cheiro-verde', category: 'Frutas e legumes' },
    { name: 'Couve-flor', category: 'Frutas e legumes' },
    { name: 'Mandioca', category: 'Frutas e legumes' },
    { name: 'Batata doce', category: 'Frutas e legumes' },
    { name: 'Hortelã', category: 'Frutas e legumes' },
    { name: 'Maracujá', category: 'Frutas e legumes' },
    { name: 'Quiabo', category: 'Frutas e legumes' },
    { name: 'Repolho', category: 'Frutas e legumes' },
    { name: 'Pepinos', category: 'Frutas e legumes' },
    { name: 'Uvas', category: 'Frutas e legumes' },
    { name: 'Uva passa', category: 'Frutas e legumes' },
    { name: 'Uva passa 200g', category: 'Frutas e legumes' },
    { name: 'Morango', category: 'Frutas e legumes' },

    { name: 'Ração', category: 'Pet' },
    { name: 'Petiscos', category: 'Pet' },
    { name: 'Tapete higiênico', category: 'Pet' },
];
